### ISSUE TITLE
Raised Error undefined `username` upon any user logins

### ISSUE THREAD

**Issue by snguyenthanh** [karrui/taskrr#28]
An error of `Cannot read property 'username' of undefined` is raised, whenever an user logins.

Although at the moment it does not affect any functional features, it should be fixed to avoid any unexpected bugs or future breakdowns.

**Comment by snguyenthanh** [comment]
Logs in as 'son_test' with password '123'.
The error is printed in stdout.

**Comment by karrui** [comment]
Fixed but not sure which commit
